Improve landing page and footer responsivity
Tietokilta/tikweb-frontend pull request #47
Opened 2022-12-04 20:38 UTC by tuukka-miettinen

2022-12-05 22:27 UTC, PurkkaKoodari requested changes

2022-12-05 22:27 UTC, PurkkaKoodari commented on src/components/Footer.tsx
> +                  className="max-h-[10vw] mx-auto"
Using `vw` for `max-height` is generally a bit sus and `max-height` tends to mess up aspect ratios.

2022-12-05 22:27 UTC, PurkkaKoodari commented on src/components/Footer.tsx
> +              <a href={url} key={name} className="grow-1 shrink-0 basis-full md:basis-1/2 lg:basis-1/3 p-3 justify-center">
Run `prettier` or use its VSCode formatter to fix the lint error.

2022-12-06 11:22 UTC, tuukka-miettinen commented on src/components/Footer.tsx
> +                  className="max-h-[10vw] mx-auto"
Yep I know it's a bit haram but I tested it with many different web browser sizes and it looked good on all of them, so I thought good enough. I will change it though when I run the prettier.

2022-12-11 11:27 UTC, PurkkaKoodari approved these changes

2022-12-11 11:27 UTC, merged